// ============================================================================
// 本文件由 build_unit_db.py 从 unit_database.sql 自动生成，请勿手工修改！
// 修改单位数值的流程：编辑 unit_database.sql -> 运行 `python build_unit_db.py`
// ============================================================================

window.UNIT_DB = {
  source: 'unit_database.sql',
  sourceSha1: '7734d808cbaf',
  // 单位数值：数据库记录（不适用或未填的列不出现在记录里）
  database: {
    // player_infantry：阵营 player，类别 infantry
    player_infantry: [
      {
        unit_id: 'JF',
        unit_name: 'JF',
        cost: 40,
        build_time: 30,
        max_hp: 30,
        armor: 8,
        move_speed: 187.5,
        action_range: 300,
        action_value: 3,
        action_cd: 0.65,
        target_type: 0,
        armor_penetration: 8,
        squad_size: 3,
        roster: ['Jiangyu', 'Qiongjiu', 'Daiyan'],
        character_scale: 0.5625,
        collision_radius: 30,
        member_collision_radius: 17,
        formation_side: 56.5,
        red_zone_clearance: 19,
        member_separation: 19,
        member_enemy_separation: 37.5,
        regen_delay: 5000,
        regen_per_second: 0.05,
        detonate_delay: 5000,
        detonate_radius: 40,
        detonate_damage: 20,
        detonate_damage_falloff: 0.2,
        detonate_falloff_step: 10,
        charge_speed: 244,
        charge_trigger_distance: 37.5,
        death_tint_duration: 900,
        death_tint_strength: 0.25,
        deploy_cost: 10,
        member_separation_max_push: 7.5,
        member_anim_max_step: 4.9,
        member_return_distance: 112.5,
        member_return_exit_ratio: 0.5,
        member_return_extra_clearance: 7.5,
        member_return_speed: 262.5,
        member_return_replan_distance: 75,
        member_return_waypoint_radius: 7.5,
        squad_regroup_arrive: 2.8,
        squad_regroup_catchup_distance: 30,
        squad_regroup_stall_ratio: 0.25,
        squad_regroup_stall_frames: 20,
        squad_free_return_ratio: 1.15,
        squad_separation_target: 28,
        squad_separation_buffer: 0.05,
        squad_order_spread: 60,
        squad_separation_passes: 6,
        squad_edge_range: 11.5,
        squad_edge_exit_range: 26.5,
        squad_formation_lerp: 0.25,
        squad_morph_duration: 560,
        squad_free_spread: 30,
        squad_free_max_distance: 86.5,
        squad_free_back_left: 11.5,
        squad_free_back_apex: -19,
        squad_free_back_right: 7.5,
        squad_slot_swap_blend: 0.97,
        animation_mix_attack: 0.12,
        animation_mix_loop: 0.16,
        attack_animation_fallback: 600,
        animation_lock_grace: 20,
        spawn_animation_duration: 720,
        spawn_animation_min_scale: 0.3,
        red_route_range: 281.5,
        red_steer_bias: 0.15,
        move_stall_timeout: 1600,
        move_progress_epsilon: 0.95,
        charge_retarget_interval: 300,
        bar_width: 37.5,
        shadow_width_ratio: 0.66,
        shadow_flatten: 0.27,
        shadow_alpha: 0.32,
        shadow_offset_y: 2,
        ring_width: 37.5,
        ring_height: 17,
        ring_offset_y: 4,
      },
    ],
    // player_heavy：阵营 player，类别 heavy_tank
    player_heavy: [
      {
        unit_id: 'tasa_air',
        unit_name: 'tasa_air',
        deploy_cost: 30,
      },
    ],
    // player_support：阵营 player，类别 medic
    player_support: [
      {
        unit_id: 'mid',
        unit_name: 'mid',
        deploy_cost: 20,
      },
    ],
    // player_merc：阵营 player，类别 inf_temp
    player_merc: [
    ],
    // enemy_infantry：阵营 enemy，类别 infantry
    enemy_infantry: [
      {
        unit_id: 'Vespid',
        unit_name: 'Vespid',
        cost: 0,
        build_time: 0,
        max_hp: 40,
        armor: 8,
        move_speed: 150,
        action_range: 180,
        action_value: 2,
        action_cd: 1.1,
        target_type: 0,
        armor_penetration: 8,
        squad_size: 1,
        roster: ['Vespid'],
        character_scale: 0.272,
        collision_radius: 20.5,
        red_zone_clearance: 19,
        detonate_delay: 3000,
        detonate_radius: 20,
        detonate_damage: 5,
        track_range: 240,
        attack_release_margin: 12,
        track_release_margin: 16,
        deploy_cost: 0,
        bar_width: 56.5,
        hold_duration: 5000,
        patrol_radius: 37.5,
        patrol_min_radius: 15,
        patrol_slack: 22.5,
        endpoint_roam_radius: 187.5,
        endpoint_idle_min: 1200,
        endpoint_idle_max: 4000,
        endpoint_return_slack_factor: 4,
        route_corridor: 38,
        route_variant_count: 5,
        spawn_offmap_padding: 90,
        separation_strength: 1,
        separation_max_push: 7.5,
        replan_cooldown: 700,
        stuck_time: 1000,
        stuck_distance: 9.5,
        attack_contact_tolerance: 2,
        attack_animation_loop: 1,
        knockback_distance: 10,
        knockback_duration: 500,
      },
    ],
    // enemy_heavy：阵营 enemy，类别 heavy_tank
    enemy_heavy: [
    ],
    // enemy_support：阵营 enemy，类别 medic
    enemy_support: [
    ],
  }
};
